### ISSUE TITLE
nagios plugins not installed

### ISSUE THREAD

**Issue by dpnl87** [Icinga/chef-icinga2#265]
While the attribute `install_nagios_plugins` is set to `true` the nagio-plugins package is not installed.

While searching trough the available recipes I was not able te find the `package` resource in charge of installation.

**Comment by vkhatri** [comment]
@dpnl87 Looks like stale attribute. `nrpe` installation was removed from the cookbook in favor of cookbooks available to manage `nrpe`.

Need to remove it from README. Please feel free to submit a PR.

**Comment by dpnl87** [comment]
Do we want to completely remove it from the cookbook or do we want to make a dependency to a `nrpe` cookbook and provide functionality to install it?

I'll have a look at creating a PR

**Comment by dnsmichi** [comment]
Users shouldn't be bound to a specific client by a dependency imho. I'd rather avoid nrpe and try to integrate the icinga 2 client natively, similar to how the Puppet module did already. Still opt-in for anyone out there.

**Comment by dpnl87** [comment]
@dnsmichi My Puppet skills are not bad, but I can't seem to find the code you are referring to. Could you point me to the part of the Manifest where the client is being installed? I will try to implement something similar with the Puppet code as inspiration.

For my current setup we still use the Nagios plugins, but if the client setup is better I have the possibility to switch :)

**Comment by bobapple** [comment]
Actually, there is no dedicated code for an Icinga 2 "client" in the puppet module. Since we always use the same binary (or package) either for a client, satellite or master, it's a matter of configuration. I think @dnsmichi is referring to the example configurations documented in [README.md](https://github.com/icinga/puppet-icinga2#clustering-icinga-2) and the [examples](https://github.com/Icinga/puppet-icinga2/tree/master/examples) directory.

In my opinion, it would be best to completely remove `nrpe` from the cookbook. It's not part of Icinga and it's not dedicated to Icinga either. And as @vkhatri already pointed out, there are other cookbooks handling `nrpe` already.

**Comment by dnsmichi** [comment]
Yep, thanks @bobapple, exactly what I was referring to.

**Comment by vkhatri** [comment]
@dpnl87 If you are still looking for `nrpe` cookbook, there is one I have been using.

https://github.com/vkhatri/chef-nrpe

**Comment by vkhatri** [comment]
Closing, as `nrpe` is not in the scope of `icinga2` cookbook.

**Comment by dpnl87** [comment]
Thnx @vkhatri. I'm looking to create a PR to remove the references.

**Comment by vkhatri** [comment]
Reopening, closed by mistake.

**Comment by vkhatri** [comment]
I mean, keeping it open in favor of PR.
